function(shoots_host_apply_warnings target_name)
  if(NOT SHOOTS_HOST_ENABLE_WARNINGS)
    return()
  endif()

  if(SHOOTS_HOST_WARNINGS_AS_ERRORS)
    set(SHOOTS_HOST_WERROR ON)
  endif()

  if(MSVC)
    target_compile_options(${target_name} PRIVATE /W4)
    if(SHOOTS_HOST_WERROR)
      target_compile_options(${target_name} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target_name} PRIVATE -Wall -Wextra -Wpedantic)
    if(SHOOTS_HOST_WERROR)
      target_compile_options(${target_name} PRIVATE -Werror)
    endif()
  endif()
endfunction()
